import type { Metadata } from "next";
import { Inter, Syne } from 'next/font/google';
import "./globals.css";

import { Roboto_Serif, Rubik } from 'next/font/google';

const baseFont = Roboto_Serif({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-space-default'
});

const displayFont = Rubik({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-space-display'
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${baseFont.variable} ${displayFont.variable} scroll-smooth`}>{children}</body>
    </html>
  );
}
